@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI3ZTIyMzk0LWFmZjMtNGVlNi1iZWE4LWYxYjIxNmY0NjIxNyIsInVzZXJOYW1lIjoiQWRtaW4xIiwicGFzc3dvcmQiOiI4ZDcxN2QwYjNmOGZmYTUzMjQzZDA3Nzg0OTkzODYyYzowYjkzN2MxODMyMDAxNjk0NzQyYWY3ZTA5NDA3ODdmMyIsImNyZWF0ZWRBdCI6IjIwMjUtMDgtMDNUMDk6MTU6MjMuMDk1WiIsImlhdCI6MTc1NDIyMDcxNiwiZXhwIjoxNzU0MjIxNDM2fQ.Lhvsb4mGH_3bTVpYjzH3feUDagww9eDUD28o2G1eKRs



###
GET http://localhost:5000/api/v1/seeder/userSeeder
Content-Type: application/json
Authorization: Bearer {{token}}



###
POST http://localhost:5000/api/v1/full-seeder/fullSeeder
Content-Type: application/json
Authorization: Bearer {{token}}


###
POST  http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{     "userName"    : "Admin1",
       "password" : "Admin123!"
}


###
POST  http://localhost:5000/api/v1/eventStub/createEventStub
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nameEvent": "Web3 Music Fest 2025",
  "location": "Jakarta, Indonesia",
  "startDate": "2025-08-15T18:00:00.000Z",
  "endDate": "2025-08-15T23:00:00.000Z",
  "totalTicket": 1000,
  "ticketPrice": 50000,
  "description": "Konser besar untuk komunitas Web3 dan NFT dengan berbagai musisi ternama.",
  "image": "https://example.com/assets/nft-banner.png",
  "categoryEvent": "BLOCKCHAIN",
  "typeEvent": "NASIONAL"
}

###
GET http://localhost:5000/api/v1/eventStub/get-all-events
Content-Type: application/json
